# triggering a new build
lang:
  python: 3.9 #the global lang and version
events: #if omitted then every event fires the build
  git_branch: master
# ops are unordered logical groupings of functionality that can (eventually) be run locally or remotely
ops: #if omitted than a default build is executed based on language
  test:
    - python:
        path: ''
        script: |
          echo "python3 version: $(python3 --version)"
          echo "pip3 version: $(pip3 --version)"
          echo "python3.9 version: $(python3.9 --version)"
    - nodejs:
        path: ''
        lang:
          nodejs: 15
        script: |
          node --version
    - java:
        path: ''
        lang:
          java: 8
        script: |
          java -version
    - go:
        path: ''
        lang:
        go: 17
        script: |
          go version
stages:
  - test:
      ops:
        - test
